version: "3.3"
services:
  spark-master:
    image: ls12styler/spark:latest
    container_name: ajibd-spark-master
    hostname: spark-master
    ports:
      - "8080:8080"
      - "7077:7077"
    environment:
      - "SPARK_LOCAL_IP=ajibd-spark-master"
      - "SPARK_MASTER_PORT=7077"
      - "SPARK_MASTER_WEBUI_PORT=8080"
    entrypoint: "/start-master.sh"
  spark-worker:
    image: ls12styler/spark:latest
    depends_on:
      - spark-master
    ports:
      - 8080
    environment:
      - "SPARK_MASTER=spark://ajibd-spark-master:7077"
      - "SPARK_WORKER_WEBUI_PORT=8080"
    entrypoint: "/start-worker.sh"
    volumes:
      - /Users/broadlea/workspace/src/github.com/ls12styler/ajibd/data:/local
  source-db:
    image: mysql:5
    volumes:
      - /Users/broadlea/workspace/src/github.com/ls12styler/ajibd/data:/local
      - /Users/broadlea/workspace/src/github.com/ls12styler/ajibd/mysql/scripts/source:/docker-entrypoint-initdb.d
    environment:
      - "MYSQL_DATABASE=source"
      - "MYSQL_USER=source"
      - "MYSQL_PASSWORD=source"
      - "MYSQL_ROOT_PASSWORD=asdfgasdasf"
    command: "--secure-file-priv=/local"
  warehouse-db:
    image: mysql:5
    environment:
      - "MYSQL_DATABASE=warehouse"
      - "MYSQL_USER=warehouse"
      - "MYSQL_PASSWORD=warehouse"
      - "MYSQL_ROOT_PASSWORD=asdfgasdasf"
    volumes:
      - /Users/broadlea/workspace/src/github.com/ls12styler/ajibd/data:/local
      - /Users/broadlea/workspace/src/github.com/ls12styler/ajibd/mysql/scripts/warehouse:/docker-entrypoint-initdb.d
  airflow:
    image: puckel/docker-airflow:latest
    command: "webserver"
    depends_on:
      - spark-worker
      - spark-master
      - source-db
      - warehouse-db
      - presentation-db
    ports:
      - "8081:8081"
    environment:
      - AIRFLOW__WEBUI__PORT=8081
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /Users/broadlea/workspace/src/github.com/ls12styler/ajibd/airflow/dags:/usr/local/airflow/dags
      - /Users/broadlea/workspace/src/github.com/ls12styler/ajibd/airflow/requirements.txt:/requirements.txt
  superset:
    image: amancevice/superset
    command: bash -c "superset-init --username admin --password admin --firstname user --lastname user --email admin@admin.org && gunicorn superset:app"
    restart: always
    depends_on:
      - presentation-db
    environment:
      MAPBOX_API_KEY: ${MAPBOX_API_KEY}
    ports:
      - "8088:8088"
    volumes:
      - /Users/broadlea/workspace/src/github.com/ls12styler/ajibd/superset:/etc/superset/
  presentation-db:
    image: mysql:5
    environment:
      - "MYSQL_DATABASE=presentation"
      - "MYSQL_USER=presentation"
      - "MYSQL_PASSWORD=presentation"
      - "MYSQL_ROOT_PASSWORD=asdfgasdasf"
    volumes:
      - /Users/broadlea/workspace/src/github.com/ls12styler/ajibd/mysql/scripts/presentation:/docker-entrypoint-initdb.d
