version: "3.3"
services:
  spark-master:
    image: ls12styler/spark:latest
    ports:
      - "8080:8080"
      - "7077:7077"
    environment:
      - "SPARK_LOCAL_IP=spark-master"
      - "SPARK_MASTER_PORT=7077"
      - "SPARK_MASTER_WEBUI_PORT=8080"
    entrypoint: "/start-master.sh"
    networks:
      - ajibd-network
  spark-worker:
    image: ls12styler/spark:latest
    depends_on:
      - spark-master
    ports:
      - 8080
    environment:
      - "SPARK_MASTER=spark://spark-master:7077"
      - "SPARK_WORKER_WEBUI_PORT=8080"
    entrypoint: "/start-worker.sh"
    volumes:
      - ./data:/local
    networks:
      - ajibd-network
  source-db:
    image: mysql:5
    volumes:
      - ./data:/local
      - ./mysql/scripts/source:/docker-entrypoint-initdb.d
    environment:
      - "MYSQL_DATABASE=source"
      - "MYSQL_USER=source"
      - "MYSQL_PASSWORD=source"
      - "MYSQL_ROOT_PASSWORD=asdfgasdasf"
    command: "--secure-file-priv=/local"
    networks:
      - ajibd-network
  warehouse-db:
    image: mysql:5
    environment:
      - "MYSQL_DATABASE=warehouse"
      - "MYSQL_USER=warehouse"
      - "MYSQL_PASSWORD=warehouse"
      - "MYSQL_ROOT_PASSWORD=asdfgasdasf"
    volumes:
      - ./data:/local
      - ./mysql/scripts/warehouse:/docker-entrypoint-initdb.d
    networks:
      - ajibd-network
  airflow:
    image: puckel/docker-airflow:latest
    command: "webserver"
    ports:
      - "8081:8081"
    environment:
      - AIRFLOW__WEBUI__PORT=8081
      - LOAD_EX=y
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./airflow/dags:/usr/local/airflow/dags
      - ./airflow/requirements.txt:/requirements.txt
    networks:
      - ajibd-network
  superset:
    image: amancevice/superset
    command: bash -c "superset-init --username admin --password admin --firstname user --lastname user --email admin@admin.org && gunicorn superset:app"
    restart: always
    depends_on:
      - presentation-db
    environment:
      MAPBOX_API_KEY: ${MAPBOX_API_KEY}
    ports:
      - "8088:8088"
    volumes:
      - ./superset:/etc/superset/
    networks:
      - ajibd-network
  presentation-db:
    image: mysql:5
    environment:
      - "MYSQL_DATABASE=presentation"
      - "MYSQL_USER=presentation"
      - "MYSQL_PASSWORD=presentation"
      - "MYSQL_ROOT_PASSWORD=asdfgasdasf"
    volumes:
        - ./mysql/scripts/presentation:/docker-entrypoint-initdb.d
    networks:
      - ajibd-network

networks:
  ajibd-network:
    driver: bridge
    ipam:
      driver: default

## https://github.com/mdmccarthyuk/minihadoop
